movies-reviews/movie/urls.py
from django.urls import path

from . import views
app_name = 'movie'

urlpatterns = [
    path('detail/<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/create', views.create_review, name='create_review'),
    path('<int:review_id>/update', views.update_review, name='update_review'),
    path('<int:review_id>/delete', views.delete_review, name='delete_review'),
    path('add/', views.add_movie, name='add_movie'),
    path('delete/<int:movie_id>/', views.delete_movie, name='delete_movie'),

]

movies-reviews/moviesreviews/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from movie import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movie_views.home, name='home'),
    path('about/', movie_views.about, name='about'),
    path('signup/', movie_views.signup, name='signup'),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies-reviews/movie/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse





class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='movie/images/')
    category = models.CharField(max_length=250)
    year = models.IntegerField(default=2000)
    release_date = models.DateTimeField(blank=True, null=True)
    actors=models.CharField(max_length=250)
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'movie'
        verbose_name_plural = 'movies'


class Review(models.Model):
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    watch_again = models.BooleanField()


    def __str__(self):
        return self.text[:40]

    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'
        db_table = 'review'

movies-reviews/movie/forms.py
from django.forms import ModelForm, Textarea
from .models import Review


class ReviewForm(ModelForm):
    """form for the reivew page."""

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['watch_again'].widget.attrs.update({
            'class': 'form-check-input'
        })

    class Meta:
        model = Review

        fields = ['text', 'watch_again']
        labels = {
            'watch_again': ('Watch Again')
        }
        widgets = {
            'text': Textarea(attrs={'rows': 4}),
        }

movies-reviews/movie/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Movie, Review

from .forms import ReviewForm


def home(request):
    """landing page"""
    search_term = request.GET.get('searchMovie')

    if search_term:
        movies = Movie.objects.filter(
            title__icontains=search_term).order_by('title')
    else:
        movies = Movie.objects.all().order_by('title')

    return render(request, 'home.html', {
        'searchTerm': search_term,
        'movies': movies
    })


def detail(request, movie_id):
    """returns detail page for the selected movie"""
    movie = get_object_or_404(Movie, pk=movie_id)
    reviews = Review.objects.filter(movie=movie)

    return render(request, 'detail.html', {
        'movie': movie,
        'reviews': reviews
    })


def about(request):
    return HttpResponse('<h1>Welcome to the about page</h1>')


def signup(request):
    email = request.GET.get('email')
    return render(request, 'signup.html', {'email': email})


@login_required
def create_review(request, movie_id):
    """creates a new review"""

    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == 'GET':
        return render(request, 'create_review.html', {
            'form': ReviewForm(),
            'movie': movie
        })
    else:
        try:
            form = ReviewForm(request.POST)
            new_review = form.save(commit=False)
            new_review.user = request.user
            new_review.movie = movie
            new_review.save()
            return redirect('detail', new_review.movie.id)
        except ValueError:
            return render(request, 'create_review.html', {
                'form': ReviewForm(),
                'error': 'Bad data passed in'
            })


@login_required
def update_review(request, review_id):
    """update a movie review"""

    review = get_object_or_404(Review, pk=review_id, user=request.user)

    if request.method == 'GET':
        form = ReviewForm(instance=review)

        return render(request, 'update_review.html', {
            'review': review,
            'form': form
        })
    else:
        try:
            form = ReviewForm(request.POST, instance=review)
            form.save()
            return redirect('detail', review.movie.id)

        except ValueError:
            return render(request, 'update_review.html', {
                'form': form,
                'error': 'Bad data in form'
            })


@login_required
def delete_review(request, review_id):
    """deletes a review"""

    review = get_object_or_404(Review, pk=review_id, user=request.user)
    review.delete()

    return redirect('detail', review.movie.id)


def add_movie(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        image = request.FILES.get('image')
        year = request.POST.get('year')
        actors = request.POST.get('actors')
        release_date = request.POST.get('release_date')
        category = request.POST.get('category')
        url = request.POST.get('url')
        if title and description and image and year and release_date and actors and category:
            movie = Movie(title=title, description=description, image=image,category=category, year=year,actors=actors,release_date=release_date, url=url)
            movie.save()
            next_url = request.POST.get('next', reverse('home'))
            return redirect(next_url)

        else:
            # Handle the case where required fields are missing
            return render(request, 'add.html', {'error': 'All fields except URL are required'})

    else:
        return render(request, 'add.html')

def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        movie.delete()
        next_url = request.POST.get('next', reverse('home'))
        return redirect(next_url)
    return render(request, 'confirm_delete.html', {'movie': movie})

movies-reviews/movie/templates/add.html
{% extends 'base.html' %}
{% block content %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title" placeholder="enter movie name"><br>
    <input type="text" name="description" placeholder="enter movie desc"><br>
    <input type="text" name="year" placeholder="enter movie year"><br>
    <input type="text" name="actors" placeholder="enter actors name"><br>
    <input type="text" name="category" placeholder="enter category name"><br>
    <input type="file" name="image" ><br>
    <input type="url" name="url" placeholder="Youtube trailer link"><br>
    <input type="date" name="release_date" placeholder="enter release date"><br>
    <input type="submit">

</form>
{% endblock %}
{% endblock %}

movies-reviews/movie/templates/confirm_delete.html
{% extends 'base.html' %}
<p>Are you sure you want to delete "{{ movie.title }}"?</p>
<form action="{% url 'movie:delete_movie' movie.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete">
</form>

movies-reviews/movie/templates/create_review.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Add Review for {{ movie.title }}</h5>
                {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Review</button>
                    </form>
                </p>

                        </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

movies-reviews/movie/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
        <div class="col-md-4">
        <img src="{{ movie.image.url }}"
        class="img-fluid rounded-start" alt="">
        </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.title }}</h5>
                    <p class="card-text">{{ movie.description }}</p>
                    <p class="card-text">
                        {% if movie.url %}
                            <a href="{{ movie.url }}" class="btn btn-primary">
                            Movie Link
                            </a>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <a href="{% url 'movie:create_review' movie.id %}"
                                class="btn btn-primary"
                            >
                                Add Review
                            </a>
                        {% endif %}
                        <hr />
                        <h3> Reviews </h3>
                        <ul class="list-group">
                            {% for review in reviews %}
                                <li class="list-group-item pb-3 pt-3">
                                    <h5 class="card-title">
                                        Review by {{ review.user.username }}
                                    </h5>
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        {{ review.date }}
                                    </h6>
                                    <p class="card-text">{{ review.text }}</p>
                                    {% if user.is_authenticated and user == review.user %}
                                        <a class="btn btn-primary" href="{% url 'movie:update_review' review.id %}"> Update </a>
                                        <a class="btn btn-danger" href="{% url 'movie:delete_review' review.id %}"> Delete </a>
                                    {% endif %}
                                </li>

                            {% endfor %}
                        </ul>
                    </p>
                </div>
            </div>

        </div>
    </div>
<form action="{% url 'movie:delete_movie' movie.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete Movie">
</form>
{% endblock content %}

movies-reviews/movie/templates/home.html
{% extends 'base.html' %}
{% block content %}
<body>
<form action="">
        <div class="mb-3">
            <label class="form-label">Search for Movie:</label>
            <input type="text" class="form-control" name="searchMovie">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
    Searching for {{ searchTerm }}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for movie in movies %}
            <div v-for="movie in movies" class="col">
                <div class="card">
                    <img class="card-img-top" src="{{movie.image.url }}" />
                    <div class="card-body">
                        <a href="{% url 'movie:detail' movie.id %}">
                            <h5 class="card-title fw-bold">{{ movie.title}}</h5>
                        </a>
                        <p class="card-text">{{ movie.description}}</p>
                        <p class="card-text">Movie Actors : {{ movie.actors}}</p>
                        <p class="card-text">Movie Category : {{ movie.category}}</p>
                        <p class="card-text">Year : {{ movie.year}}</p>
                        <p class="card-text">Released on : {{ movie.release_date}}</p>
                            {% if movie.url %}
                        <a href="{{ movie.url }}" class="btn btn-primary">Youtube trailer link</a>

                        {% endif %}


                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <br />
    <br />
<a class="btn btn-primary" href="{% url 'movie:add_movie' %}">Add Movie</a>
{% endblock content %}
</body>

movies-reviews/movie/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2>Added {{ email }} to the mailing list!</h2>
        <a href="{% url 'home' %}">Home</a>
    </div>
</body>
</html>

movies-reviews/movie/templates/update_review.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Update Review for {{ movie.title }}</h5>
                {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Update Review</button>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}